### ISSUE TITLE
Game start failed because of ttkbootstrap. (AC-9)

### ISSUE THREAD

**Issue by Xuangeaha** [Xuangeaha/Apple-Clicker#9]
Beta 0.2.0, when l started the game this occured:

```
Traceback (most recent call last):
  File "E:\巨型垃圾桶\3\Apple Clicker\Apple_Clicker_beta0.2.0\apple clicker.pyw", line 986, in <module>
    style = Style(theme='apple7')
  File "C:\Users\xiang\AppData\Local\Programs\Python\Python310\lib\site-packages\ttkbootstrap\style.py", line 490, in __init__
    self.theme_use(theme)
  File "C:\Users\xiang\AppData\Local\Programs\Python\Python310\lib\site-packages\ttkbootstrap\style.py", line 600, in theme_use
    raise TclError(themename, "is not a valid theme.")
_tkinter.TclError: ('apple7', 'is not a valid theme.')
```

**Comment by Xuangeaha** [comment]
Fixed

**Comment by Xuangeaha** [comment]
ttkbootstrap is making me mad
